### ISSUE TITLE
[Feature]: Is there any method for upgrading existing plan/subscription in it?

### ISSUE THREAD

**Issue by pushkarsingh32** [PaddleHQ/paddle-js-wrapper#35]
### Tell us about your feature request

I would like to have user ability to upgrade their subscription/one time cost product. 
Is this possible? Thanks

### What problem are you looking to solve?

Ability to upgrade in one click for user

### How important is this suggestion to you?

Important

**Comment by pushkarsingh32** [comment]
Okay. 

Thing is on your upgrade subscription doc we need to send subscription id.

 It makes sense for subscription product.

 But how things will work when there is no subscription id ( for one time cost product) as it come null.
Thanks

**Comment by vijayasingam-paddle** [comment]
Hi @pushkarsingh32, 
I think there is some confusion here. 

Subscriptions are like memberships where you pay regularly for ongoing access. You can upgrade to get more features. However, One-time products are bought once and cannot be upgraded or downgraded.

Please let us know if you need any other information.
