### ISSUE TITLE
[Bug]: Property updateCheckout does not exist on type Checkout

### ISSUE THREAD

**Issue by gorshkovaea** [PaddleHQ/paddle-js-wrapper#36]
### What happened?

I attempted to update a checkout form with new items and reset a discount using the following code 
`paddle.Checkout.updateCheckout({
    discountId: null,
    items: [{ priceId: 'newPriceId', quantity: 1 }],
 });
`
However, I encountered a TypeScript error stating "Property updateCheckout does not exist on type".
Nonetheless, there is a documentation for this method [here](https://developer.paddle.com/paddlejs/methods/paddle-checkout-updatecheckout), and also I was able to use it successfully by casting to 'any' as follows:
`(paddle.Checkout as any).updateCheckout({
    discountId: null,
    items: [{ priceId: 'newPriceId', quantity: 1 }],
 });
`.

Why can't I reach updateCheckout in my ts code without an error? 

### Steps to reproduce

1. Call paddle.Checkout.updateCheckout in .ts file
2. Get a ts error "Property updateCheckout does not exist on type"

### What did you expect to happen?

paddle.Checkout.updateCheckout() works well without any errors

### How are you integrating?

React, TypeScript

**Comment by vijayasingam-paddle** [comment]
Hi @gorshkovaea,
I have released a new version with the type definition for `updateCheckout` function. 
Please update to the latest version (`1.1.1`)

Thank you.
