### ISSUE TITLE
[Bug]: User changing email address is ignored

### ISSUE THREAD

**Issue by thomasdondorf** [PaddleHQ/paddle-js-wrapper#41]
### What happened?

I'm using the following code to open the checkout:

```js
paddle.Checkout.open({
    items: [{ /* ... */ }],
    customer: {
        email: 'test@example.com'
    },
});
```

I'm prefilling the email address for my users. So my users should be able to change the email address if they want. I'm also not setting `allowLogout: false` in `settings`. So, per documentation, the user should be able to change his email address.

But, Paddle seems to ignore the email address change. See the GIF below.

![paddle-email-bug](https://github.com/PaddleHQ/paddle-js-wrapper/assets/13748265/39e94e7a-f7a4-4b0a-a751-f9946f82fb9e)

IMHO this is a serious bug, as Paddle progresses with the wrong email address.

### Steps to reproduce

1. I'm prefilling `test@example.com` via code above.
2. User changes email to `foo@bar.com` (and enters ZIP code), then clicks "Continue".
3. **The email address is not changed!** The event `checkout.customer.updated` is fired, but the email address is the wrong/old one.
5. Only when the user goes back to the first step **again** and changes the email address again, the email change is processed.

### What did you expect to happen?

I expected the user to be able to change his email address as per documentation.

### How are you integrating?

React with @paddle/paddle-js - version 1.0.2

**Comment by vijayasingam-paddle** [comment]
Hi @thomasdondorf,
Thank you for raising this bug report. 

I am sorry that you are running into this issue. I checked with our team and they were already working towards fixing it.
I will let you know once it is fixed. 

Thank you.

**Comment by vijayasingam-paddle** [comment]
Hi @thomasdondorf,

Thank you for being patient with us. 
This issue has been fixed. Now users can change their email address on the first screen and our checkout will pick up the latest value.

Please let us know if we can help with anything else. 

Thank you.

**Comment by thomasdondorf** [comment]
Awesome, thanks for the update!
