### ISSUE TITLE
[Bug]: Incorrect type definition of discountId in updateCheckout

### ISSUE THREAD

**Issue by gorshkovaea** [PaddleHQ/paddle-js-wrapper#49]
### What happened?

I got an error "Type null is not assignable to type string | undefined" when I tried to call  
`paddle.Checkout.updateCheckout({ discountId: null, items: [{ priceId: 'newPriceId', quantity: 1 }], });`. 

I expect the type of _discountId_ to be _string | null_, as [docs](https://developer.paddle.com/paddlejs/methods/paddle-checkout-updatecheckout) state

### Steps to reproduce

1. Call paddle.Checkout.updateCheckout in .ts file with discountId: null
2. Get a ts error "Type null is not assignable to type string | undefined"

### What did you expect to happen?

`paddle.Checkout.updateCheckout({ discountId: null, items: [{ priceId: 'newPriceId', quantity: 1 }], });` works well without any errors

### How are you integrating?

React, TypeScript

**Comment by vijayasingam-paddle** [comment]
Hi @gorshkovaea,
Thank you for reporting this issue to us. 
I am sorry that you are running into this issue. We will check and update the types.

Thank you.

**Comment by vifer** [comment]
Hey @gorshkovaea This should be fixed now in version 1.2.3
