### ISSUE TITLE
[Bug]: Missing type price_name in CheckoutEventsItem

### ISSUE THREAD

**Issue by JonasGruenwald** [PaddleHQ/paddle-js-wrapper#51]
### What happened?

According to the Paddle.js docs, checkout event items contain a nullable property `price_name`, see: https://developer.paddle.com/paddlejs/general/checkout-loaded

This property is indeed present on `items` returned by checkout events, but there is no type for this specified in the `CheckoutEventsItem` interface, only for `price_id`, making it difficult to access when using typescript.

### Steps to reproduce

1. Attempt to access `price_name` on a `CheckoutEventsItem`.
2. TypeError: Property 'price_name' does not exist on type 'CheckoutEventsItem'.

### What did you expect to happen?

The key should exist on the property

**Comment by vijayasingam-paddle** [comment]
Hi @JonasGruenwald,
Thank you for raising this issue to us. 

I am sorry, this change must have slipped through us. I have added the property now and released a new version `1.2.1`. 

Please let us know if we can help you with anything else. 

Thank you.

**Comment by chrisjansky** [comment]
Hello,

On a similar note: I am trying to type the body request for `https://sandbox-api.paddle.com/transactions`, I assume `TransactionPreviewItem` type is the correct format for `items`.

The problem is the TS interface expects camelCase in keys (such as `unitPrice`) whereas the stringified JSON needs snake_case (`unit_price`) in the fetch request. Is that an expected behavior and do I need to transform the keys myself?

Here’s the full snippet that should be correct:
```
const payItems: TransactionPreviewItem[] = [
            {
                quantity: 1,
                price: {
                    product: {
                        name: "Test Product",
                        taxCategory: "standard",
                    },
                    name: "Test Subtitle",
                    description: "Test Product Description",
                    unitPrice: {
                        amount: "111",
                        currencyCode: "EUR",
                    },
                },
            },
        ]
```

But throws this error on request:
```
0: {field: 'items.0.price', message: 'unit_price is required'}
1: {field: 'items.0.price', message: 'Additional property unitPrice is not allowed'}
```

Thanks.

**Comment by vijayasingam-paddle** [comment]
Hi @chrisjansky,
Thank you for raising this to us. 

To understand this further, please let us know if you are using our SDK or any other library to call our API. 
Our APIs will expect and return keys in the snake case. As snake case is not the standard in JavaScript for keys, our SDK will convert them to camel case before returning them to the users. 

Looking at the code and the error message, I believe you are calling the API directly as you are getting an error related to the casing. 

Unfortunately, we don't have types for directly calling our API with the snake case. I will add it to our backlog to get the types added in the snake case too, but I am afraid it won't be quick.

If you don't mind me asking is there any reason to not use our SDK?

**Comment by chrisjansky** [comment]
Hello @vijayasingam-paddle, 

Thanks for your reply.

Quick description of my tech stack: I am hitting `https://sandbox-api.paddle.com/transactions` directly via `fetch()` on front-end using Nuxt 3 server route. The fulfilment of the transaction is handled via the SDK in a cloud function.

Here’s the code to create a `transactionId` to pass to `Paddle.Checkout.open()` from `@paddle/paddle-js`:

```
const transaction: { data: { id: string } } = await fetch("https://sandbox-api.paddle.com/transactions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer ...",
      },
      body: JSON.stringify({ items: payItems }, snakeCaseReplacer),
    }).then((response) => response.json())

    return transaction.data.id
```

That actually works now as I implemented a `snakeCaseReplacer` to transform `unit_price` to `unitPrice` et c.

Going back to your reply, I should avoid calling the endpoints directly and use `paddle-node-sdk` even on front-end?

Thank you.

**Comment by vijayasingam-paddle** [comment]
Hi @chrisjansky, 
I am glad that you were able to make it work. 

> I should avoid calling the endpoints directly and use paddle-node-sdk even on front-end?

Sorry, I did not mean to say you `should` use our node SDK in server side routes of your frontend. I meant that you `can` use our node SDK on the server side as it makes your life a little easy.

> create a transactionId to pass to Paddle.Checkout.open() from @paddle/paddle-js:

Just out of my personal curiosity, can you please share why you decided to go this way instead of directly passing the `priceId` and `quantity` to `Paddle.Checkout.open()` function? is it because you don't want your customers to change the quantity? 

There is nothing wrong with this approach, I am just trying to understand how users use our platform to meet their requirements.

Please feel free to reach out to us if you have any other questions. 

Thank you.

**Comment by chrisjansky** [comment]
@vijayasingam-paddle Thanks for the quick reply.

> can you please share why you decided to go this way ...

I am building a checkout to purchase fonts – each font cart has a unique license and combination of fonts, so the product(s) are created on the fly along with the prices calculation returned separately from back-end.

I am now building a `transaction.completed` webhook to process the order on the server. Is there any helper function in the node SDK to help the conversion from snake_case to camelCase?

So far I have this:
```
import { TransactionNotification } from "@paddle/paddle-node-sdk"
const app = express()

app.post("/transaction/fulfil", async (request: { body: { data: TransactionNotification } }, response) => {
  logger.info("Transaction received successfully")
  const { data } = request.body
  logger.info("Billed at:", data.billedAt) // => undefined, should be billed_at
})
```

This snipped is typed correctly, but returns `undefined` in runtime. Should I do it differently?

Thanks.

**Comment by vijayasingam-paddle** [comment]
Hello @chrisjansky,
For processing webhooks, I strongly recommend using our `webhooks.unmarshal` function. It will handle webhook signature verification and return a typed instance of the event you want to process. You can see an example [here](https://github.com/PaddleHQ/paddle-node-sdk/blob/main/README.md#webhook-signature-verification). 

PS: I can see you are using `express`, so please ensure you are sending raw request to the `unmarshal` function. Passing in a JSON request will not work.

Thank you.
