### ISSUE TITLE
[Bug]: Inline Checkout for Payment Method Update shows "Add Discount" and "Add VAT number"

### ISSUE THREAD

**Issue by Bastian** [PaddleHQ/paddle-js-wrapper#59]
### What happened?

When creating a payment method update transaction and opening it as an overlay transaction, you get the following UI:
![image](https://github.com/user-attachments/assets/d759e2e4-a811-4598-9ae3-0965b483289a)

However, when using an inline checkout, the options "Add Discount" and "Add VAT number" become available:
![image](https://github.com/user-attachments/assets/66bab49d-9c62-403a-bb4a-e1cc45a9c341)

### Steps to reproduce

1. Create a payment method update transaction
2. Open the transaction with an overlay checkout
3. Open the transaction with an inline checkout

### What did you expect to happen?

The inline checkout should not have the options to add a discount or VAT number.

**Comment by vijayasingam-paddle** [comment]
Hi @Bastian, 
Thank you for bringing this issue to our attention. 

I agree, they should not be there in the inline checkout. I will check and let you know once it is fixed. 

Thank you.

**Comment by vifer** [comment]
Hi @Bastian this has been fixed already, feel free to open a new issue if there is something else.
