### ISSUE TITLE
[Bug]: TypeError: null is not a function Error in Paddle.js cdn version 1

### ISSUE THREAD

**Issue by tejakshak** [PaddleHQ/paddle-js-wrapper#64]
### What happened?

We are facing one issue in the "https://cdn.paddle.com/paddle/paddle.js"  Only in safari browser can you look into it been triggered continuosly 
<img width="1512" alt="Screenshot 2024-10-03 at 5 57 02 PM" src="https://github.com/user-attachments/assets/7ab9ea7a-7c93-4295-9449-5974bdea6b15">

### Steps to reproduce

1. Goto https://globaldelight.com/boom in safari browser.
2. Inspect and check the console log.

### How are you integrating?

Using Javascript

**Comment by danbillson** [comment]
Thank you for reporting this issue! We will look into it and provide an update soon.

**Comment by danbillson** [comment]
Hi @tejakshak, we believe the issue to be a conflict between [core-js/stable](https://github.com/zloirock/core-js/tree/master/packages/core-js/stable) which we use for ES5 polyfilling and the angular polyfills where the global console is replaced and causes this error

**Comment by tejakshak** [comment]
Any solution to fix this ?

**Comment by tejakshak** [comment]
Hey @danbillson , 
Do we have any solution which can fix this issue ? it will be fixed in the cdn or from our end do we need to handle from the our end ?

**Comment by vifer** [comment]
> Hey @danbillson , Do we have any solution which can fix this issue ? it will be fixed in the cdn or do we need to handle from the our end ?

Hey @tejakshak unfortunately you might need to handle it in your end as those polyfills are needed to keep Paddle.js v1 compatibility with IE. 

Please reach out to us if you need help with anything else.

Thank you.

**Comment by tejakshak** [comment]
We are facing an issue related to the paddle.js file when using Safari, which is one of the most widely used browsers among our users. The problem seems to stem from the CDN serving the file, but modifying and saving the paddle.js file locally isn't recommended or ideal.

Could you please provide guidance on how we can handle this issue from our end without modifying the paddle.js file locally? Is there a workaround or a check that can be implemented from your end or recommended for us to handle Safari-specific issues?

**Comment by danbillson** [comment]
@tejakshak I can see you're currently loading the paddle script asynchronously in the body, is it possible to try and put this in the head and remove the `async` as recommended in the docs - https://developer.paddle.com/paddlejs/include-paddlejs#manual ?

There are known issues with core-js and zone.js which is also imported in the head
```
<script async="" src="https://unpkg.com/zone.js"></script>
```
it might be worth checking if there is a specific order they should be loaded and wether `async` needs to be removed from zone.js as well

**Comment by tejakshak** [comment]
Hey @danbillson , 
Thanks for the response the issue has been fixed after moving the cdn to the HEAD block,
But as per the below documentation it was under the BODY section in the implementation so we used the same, Pls update the documentation for the V1 if possible. Once again thanks for the solution.
https://developer.paddle.com/classic/getting-started/e830fe7b3cdc1-add-a-paddle-button-to-your-web-page
