### ISSUE TITLE
[Bug]: Empty Customer Name

### ISSUE THREAD

**Issue by krpano** [PaddleHQ/paddle-js-wrapper#65]
### What happened?

Hello, I'm trying to migrate to Paddle and use the paddle.js checkout.
But on every order (sandbox or real) the custom name is always empty!
On the invoice there is also just an email, nothing else, no name, no address...?

**Comment by danbillson** [comment]
Apologies for the delay in getting back to you. Thank you for reporting this issue! We will look into it and provide an update soon.

**Comment by danbillson** [comment]
Hi @krpano, I might need some more information on how you're trying to access the customer name, the recommended way to do this is through the [transaction.completed](https://developer.paddle.com/webhooks/transactions/transaction-completed) webhook

**Comment by krpano** [comment]
Hi,
right, I was using the webhook and the transaction.completed event,
and then there the customer_id to get the customer information using the "customers/customer_id" API,
but in any case the 'name' is null (also on the Paddle website in the Customers section).

E.g. here the json returned by the customers API:
```
{
  "data": {
    "id": "XXX",
    "status": "active",
    "custom_data": null,
    "name": null,
    "email": "test@test.test",
    "marketing_consent": false,
    "locale": "de",
    "created_at": "XXX",
    "updated_at": "XXX",
    "import_meta": null
  },
  "meta": {
    "request_id": "XXX"
  }
}
```

**Comment by danbillson** [comment]
Ahh right okay, we don't actually capture the customer name during checkout, I believe this is something that you would have to update https://developer.paddle.com/api-reference/customers/update-customer

**Comment by krpano** [comment]
But isn't that a problem?
Invoices without any names and only an email address???!

See here - 'Invoices - what they must include':
https://www.gov.uk/invoicing-and-taking-payment-from-customers/invoices-what-they-must-include

I can't use Paddle as long this isn't solved...

**Comment by danbillson** [comment]
Are you able to share your implementation for creating the invoice? 

There are related docs for this here - https://developer.paddle.com/build/invoices/create-issue-invoices

**Comment by krpano** [comment]
I'm not using a custom implementation, only the paddle.js checkout:

```
<script src="https://cdn.paddle.com/paddle/v2/paddle.js"></script>

<script type="text/javascript">
	
	Paddle.Initialize({token:"XXX", checkout:{settings:{showAddTaxId:true}}});
	
	function checkout()
	{
		Paddle.Checkout.open({items:[{priceId:"XXX", quantity:1}]});
	}
	
</script>
	
```

**Comment by danbillson** [comment]
@krpano I don't think the issue you are facing is necessarily related to the lib, your best bet might be contacting our customer support team at [sellers@paddle.com](mailto:sellers@paddle.com). We are closing this issue for now, but please don't hesitate to reach out if you have further questions.
