### ISSUE TITLE
[Bug]: Typescript types do not support "saved_payment_methods"

### ISSUE THREAD

**Issue by ferenckv** [PaddleHQ/paddle-js-wrapper#78]
### What happened?

Typescript types do not include typings to show saved payment methods in the checkout. 
Setting a customerAuthToken do not fails but only because its treated by typescript as an "extra" property but it's not included in the definition.

See [1](https://github.com/PaddleHQ/paddle-js-wrapper/blob/main/types/checkout/checkout.d.ts#L100C13-L100C33) & [2](https://github.com/PaddleHQ/paddle-js-wrapper/blob/main/types/shared/shared.d.ts#L4)

### Steps to reproduce

1. Setup paddle-js using https://www.npmjs.com/package/@paddle/paddle-js
2. Add `customerAuthToken` to `checkout.open`. Typescript does not complain. If you run it, it works.
3. Add `allowedPaymentMethods: ["saved_payment_methods"]` to checkout or global settings. Typescript complains.
...

### What did you expect to happen?

Types to be up to date to `paddle-js` implementation.

### How are you integrating?

React

**Comment by danbillson** [comment]
Hi @ferenckv, this type support is now available in `v1.3.3`, see https://github.com/PaddleHQ/paddle-js-wrapper/pull/81 for the relevant changes

Thanks again for raising!
